// const {findLargest} = require('./largestNumber')
const majorityElement = require('./majorityElement')
const maxSubSum = require('./maxSubSum')
// require('./patterns')
// require('./nvidiaApi')
// require("./armstrongNumber")
// require("./array/removeElement")
// require("./array/remvoeDuplicateFromSortedArray")
// require("./array/reverseString")
// require("./array/BestTimetoBuyandSellStock")
// require("./array/mergeSortedArray")
// require("./array/removeZeros")
// require("./array/LongestSubarraySumK")
// require("./array/LongestSubarraySumKWithNegatives")
// require("./searchingAndSorting/binarySearch")
// require("./searchingAndSorting/insertionSort")
// require("./searchingAndSorting/selectionSort")
// require("./linkedList/middleNode")
// require("./linkedList/reverseList")
// require("./linkedList/removeLinkedListElement")
// require("./linkedList/removeNthElement")
// require("./linkedList/roteteLinkedList")
// require('./linkedList/oddEven')
// require("./linkedList/addTwoNumber")
// require("./linkedList/mergeTwoSorted")
// require("./searchingAndSorting/bubbleSort")
// require("./searchingAndSorting/mergeTwoSortedArray")
// require("./searchingAndSorting/mergeSort")
// const { sortColors } = require('./setColors')
// require("./converStringInCommaSeprateNumber")
// require("./string/lengthOfLastWord")
// require("./string/FindWordsContainingCharacter")
// require("./string/jewelsStones")
// require("./string/FindMostFrequentVowelConsonant")
// require("./string/reverseString")
// require("./string/validPalindrom")
// require("./string/findLongestOdd")
// require("./string/LongestCommonPrefix")
require("./string/isAnagram")
const arr = [4, 2, 9, 9, 10]
// findLargest(arr)
// sortColors([2, 0, 2, 1, 1, 0])
// console.log(majorityElement([2,2,1,1,1,2,2]))
// console.log(maxSubSum([-2, 1, -3, 4, -1, 2, 1, -5, 4]))
